---
- Infrastructure:
    - Homepage:
        href: "https://home.qfhuang.pw"
        description: "Service portal"
        icon: "homepage.png"
    - Traefik Dashboard:
        href: "https://traefik.qfhuang.pw"
        description: "Reverse proxy dashboard"
        icon: "traefik.png"
    - Vaultwarden:
        href: "https://vaultwarden.qfhuang.pw"
        description: "Password manager"
        icon: "vaultwarden.png"
    - CLIProxyAPI:
        href: "https://cpa.qfhuang.pw/management.html"
        description: "CLI proxy API"
        icon: "mdi-api"
